---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-client
spec:
  selector:
    matchLabels:
      app: app-client
  replicas: 1
  template:
    metadata:
      labels:
        app: app-client
    spec:
      containers:
        - name: social-media-2024-v1-app-client
          image: soyeb88/social-media-2024-v1-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: social-media-2024-v1-app-client-service
spec:
  type: NodePort
  selector:
    app: app-client
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 31000
